backend:
  name: github
  repo: alexbraeken/gatsby-netlify
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'
  

media_folder: gatsby-starter-netlify-cms/static/img
public_folder: gatsby-starter-netlify-cms/src/img

collections:
  - name: "blog"
    label: "Blog"
    folder: "gatsby-starter-netlify-cms/src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "activity"
    label: "Activity"
    folder: "gatsby-starter-netlify-cms/src/activities"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "activity-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Visible Link", name: "visibleLink", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "teamMembers"
    label: "Team Members"
    folder: "gatsby-starter-netlify-cms/src/teamMembers"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "team-member"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Job Title", name: "jobTitle", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "position", name: "position", widget: "string"}

  - name: "algarveSlides"
    label: "Algarve Natural Parks and Reserves"
    folder: "gatsby-starter-netlify-cms/src/algarveSlides"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "algarve-slide"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Visible Link", name: "visibleLink", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featuredimage", widget: image}

  - name: "pages"
    label: "Pages"
    files:
      - file: "gatsby-starter-netlify-cms/src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "gatsby-starter-netlify-cms/src/pages/algarve/index.md"
        label: "The Algarve"
        name: "algarve"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "algarve-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: "Feature Section", name: featureSection, widget: object, fields: [{label: Images, name: imgs, widget: object, fields: [{label: "Image 1", name: img1, widget: image},{label: "Image 2", name: img2, widget: image}, {label: "Image 3", name: img3, widget: image}, {label: "Image 4", name: img4, widget: image}]}, {label: "Image Texts", name: text, widget: object, fields: [{label: "Text 1", name: text1, widget: text}, {label: "Text 2", name: text2, widget: text}, {label: "Text 3", name: text3, widget: text}, {label: "Text 4", name: text4, widget: text}]}]}
      - file: "gatsby-starter-netlify-cms/src/pages/travelerTips/index.md"
        label: "Traveler Tips"
        name: "travelerTips"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "travelerTips-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Full_image, name: full_image, widget: image}
      - file: "gatsby-starter-netlify-cms/src/pages/team/index.md"
        label: "Meet The Team"
        name: "team"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "team-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}